pipeline {
    agent any
    tools {
        maven "Maven"
        jdk "JDK"
    }
    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
        stage('Build') {
            steps {
                dir('springboottest'){
                sh 'mvn -B -DskipTests clean package'
                }
            }
       }
        stage('Test') {
            steps {
                dir('springboottest'){
                sh 'mvn test'
                }
            }
       }
        stage('Install') {
            steps {
                dir('springboottest'){
                sh 'mvn -B -DskipTests clean install'
                }
            }
       }
        stage('Build Docker Image'){
            steps{
                dir('springboottest'){
                    sh 'docker build -t springboottest-docker-image .'
                }
            }
	}
	stage('Pushing to ECR') {
     	    steps{  
               script {
                sh """docker tag springboottest-docker-image:latest 780315893543.dkr.ecr.us-east-1.amazonaws.com/springboottest-docker-image:latest"""
                sh """docker push 780315893543.dkr.ecr.us-east-1.amazonaws.com/springboottest-docker-image:latest"""
         }
        }
      }   
    }
}
